### ISSUE TITLE
Wrong escape generated

### ISSUE THREAD

**Issue by SolitudeSF** [Patitotective/kdl-nim#13]
```nim
import kdl
echo toKdlVal("'").`$`.parseKdl
```
fails at runtime with
```
Error: unhandled exception: Invalid escape ''' at 1:2
  1 | "\'"
       ^
 [KdlLexerError]
```

**Comment by Patitotective** [comment]
Hey, just fixed this in the new version v2.0.3.
The problem was that I was using Nim's `addQuoted` procedure which didn't know about KDL specific escaping rules. :sweat_smile:
